%%{init: {'theme':'base'}}%%
flowchart LR
    subgraph Numerical Modeling
    direction TB
        hydvar[/Hydrodynamic: variables <br> - Hs Offshore <br> - Peak Period <br> - Offshore water level /]-->numericalmodel
        vegvar[/Vegetation variables: <br> - Canopy height <br> - trunk thickness <br> - Root Type/Species <br> - Forest Width /] -->numericalmodel
        morphvars[/Morpodynamic Variables: <br> - bathymetry <br> - offshore slope/] --> numericalmodel
        numericalmodel[Numerical Model, either <br> - SWAN <br> - Xbeach <br> - SWASH]
    end

    numericalmodel --> |model run for each variable combination| sampleddata

    subgraph Statistical Modeling
        direction TB
        mangroveheight[/Global <br>Canopy <br>Height/] 
        metocean[/Global<br>Metocean<br>data/] --> estimator
        mangroveheight --> aleqns[Allometric Equations] --> estimator 
        sampleddata[(Synthetic <br>Database)] -->|Train Bayesian network| estimator[Bayes Net]
        dem[/Global DEM/] --> estimator
        mangroveheight --> estimator
    end 

    estimator --> FRoutput[/Global map/]

    