%%{init: {'theme':'forest'}}%%
flowchart TD
    %% 
    ph[/Raw Photon data from Icesat-2/] 
    strip_high[Remove any photon with a Z value greater than +5 msl]
    strip_lo[Remove any photon with a Z value less than -40 msl]
    msl[Find sea level by rolling median of NASA signal photons]
    SNsplit[Classify signal vs noise]
    msldata[/Local Sea Level data/]
    tidemodel[/local tidal elevation from model/]
    tides[Convert ellipsoidal height to MSL]
    mov_avg_seafloor[Find seafloor by moving average]
    seafloorheight[/Seafloor Elevation/]
    uncorr[/Uncorrected depth/]
    refr[Refraction correction]
    msl-->|surface photons| msldata --> uncorr

    SNsplit -->|Bathymetric signal photons| mov_avg_seafloor-->seafloorheight --> uncorr
    %%SNsplit --> |Noise photons| disc[Discard]
    tidemodel-->tides
    ph-->tides-->strip_high-->strip_lo-->msl 
    msl-->|Subsurface photons|SNsplit
    uncorr --> refr --> bathydata[/Nearshore Bathymetry Depth/]


