flowchart TD
    osmcoastline[/Openstreetmap 2021 coastline data/]
    mangroveextent[/Global Mangrove Watch 2016 extent/]
    reproject[Reproject WGS84 -> Pseudo-mercator]
    buffer[Buffer 500 meters]
    simplify[simplify with tolerance of 10m]
    removeholes[Remove Polygon Holes]
    osmcoastline-->reproject
    mangroveextent-->reproject -- Mangrove Extent --> removeholes
    removeholes --> buffer --> simplify --> genmangr[/Generalized Mangrove polygons/]
    reproject -- Coastlines --> splitcoast[Split coastline into 100km sections]
    spatselect[Select all coastlines that are touching a mangrove polygon]
    splitcoast -- Split Coastlines -->spatselect
    genmangr -- Extent Polygons --> spatselect
    spatselect --> manc[/Mangrove Coast Dataset/] --> sside_buf[Single-side buffer in offshore direction]
    dissolve[Dissolve]


