flowchart TD
    subgraph Already Implemented
    gebco[GEBCO Data]
    icesatphoton[ICESat-2 Photons]
    kdeinterp[/Bathymetric Signal Finding/]
    bathymetricpoint[Point Bathymetry data]
    gebcointerp[Interpolated GEBCO]
    kriging[/Universal Kriging/]
    uncertainty[ICESat-2 Uncertainty]
    icesat2surface[ICESat-2 Surface]
    interp[/Interpolate to 50m/]
    kalman_update[/Kalman Update equation/]
    upsampled_gebco[Updated Bathymetric Raster]
    icesatphoton-->kdeinterp-->bathymetricpoint-->kriging
    kriging-->uncertainty
    kriging-->icesat2surface
    gebco-->interp-->gebcointerp
    gebcointerp-->kalman_update
    icesat2surface --> kalman_update
    uncertainty --> kalman_update
    kalman_update-->upsampled_gebco
    end
    subgraph Future Steps
    otherbathy[Other Bathymetric Data Sources] --> kalman_update


    end