%%{init: {'theme':'base'}}%%
gantt
    title Max Lindsay Thesis Schedule

    dateFormat YYYY-MM-DD
    Meeting 1: milestone, m1, 2022-04-16
    section Literature Review
    Literature Review :lr, 2022-02-22,6w
    coding tasks: code, after lr, 2w 